// <auto-generated />
using System;
using DevCenterGallery.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevCenterGallery.Web.Migrations
{
    [DbContext(typeof(DevCenterContext))]
    [Migration("20200909071526_intialCreate")]
    partial class intialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("DevCenterGallary.Common.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FileInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PackageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileInfoId");

                    b.HasIndex("PackageId");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("DevCenterGallary.Common.Models.FileInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SasUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileInfo");
                });

            modelBuilder.Entity("DevCenterGallary.Common.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Architecture")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageVersion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PackgeFileInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreinstallKitStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetPlatformId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PackgeFileInfoId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("TargetPlatformId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("DevCenterGallary.Common.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DevCenterGallary.Common.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("DevCenterGallary.Common.Models.TargetPlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TargetPlatform");
                });

            modelBuilder.Entity("DevCenterGallary.Common.Models.Asset", b =>
                {
                    b.HasOne("DevCenterGallary.Common.Models.FileInfo", "FileInfo")
                        .WithMany()
                        .HasForeignKey("FileInfoId");

                    b.HasOne("DevCenterGallary.Common.Models.Package", null)
                        .WithMany("Assets")
                        .HasForeignKey("PackageId");
                });

            modelBuilder.Entity("DevCenterGallary.Common.Models.Package", b =>
                {
                    b.HasOne("DevCenterGallary.Common.Models.FileInfo", "PackgeFileInfo")
                        .WithMany()
                        .HasForeignKey("PackgeFileInfoId");

                    b.HasOne("DevCenterGallary.Common.Models.Submission", null)
                        .WithMany("Packages")
                        .HasForeignKey("SubmissionId");

                    b.HasOne("DevCenterGallary.Common.Models.TargetPlatform", "TargetPlatform")
                        .WithMany()
                        .HasForeignKey("TargetPlatformId");
                });

            modelBuilder.Entity("DevCenterGallary.Common.Models.Submission", b =>
                {
                    b.HasOne("DevCenterGallary.Common.Models.Product", null)
                        .WithMany("Submissions")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
